name: Test Runs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4

        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: MVN Clean
        run: mvn clean test
      - name: Output the Reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: TestReport
          path: ./Reports/
